import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ViewTransitions } from 'next-view-transitions'

import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html
        lang='en'
        className='scroll-smooth antialiased'
        suppressHydrationWarning
      >
        <body className={`min-h-screen ${inter.className}`}>
          <main>{children}</main>
        </body>
      </html>
    </ViewTransitions>
  )
}
